// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC4LgIk1Nu5UU8sBSgME8sU2-vaVf-hI2Q',
    appId: '1:794843970777:web:facffb631f895d3faa12c8',
    messagingSenderId: '794843970777',
    projectId: 'nha-223',
    authDomain: 'nha-223.firebaseapp.com',
    storageBucket: 'nha-223.firebasestorage.app',
    measurementId: 'G-Q50PPDYKKC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBn-tWbaVZ_CG7YxTszxHDXVud_zemZh5w',
    appId: '1:794843970777:android:cd55d8454fdb30aeaa12c8',
    messagingSenderId: '794843970777',
    projectId: 'nha-223',
    storageBucket: 'nha-223.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDRboO5ldF-HqPRlOEOBFfM6Pmoz_YcRkE',
    appId: '1:794843970777:ios:109477858771c7f0aa12c8',
    messagingSenderId: '794843970777',
    projectId: 'nha-223',
    storageBucket: 'nha-223.firebasestorage.app',
    iosClientId: '794843970777-v4nqb9gn4pmfgkmsfg2p06ggc0l24rh9.apps.googleusercontent.com',
    iosBundleId: 'com.example.finalDepiProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDRboO5ldF-HqPRlOEOBFfM6Pmoz_YcRkE',
    appId: '1:794843970777:ios:109477858771c7f0aa12c8',
    messagingSenderId: '794843970777',
    projectId: 'nha-223',
    storageBucket: 'nha-223.firebasestorage.app',
    iosBundleId: 'com.example.finalDepiProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC4LgIk1Nu5UU8sBSgME8sU2-vaVf-hI2Q',
    appId: '1:794843970777:web:61ed806631c77901aa12c8',
    messagingSenderId: '794843970777',
    projectId: 'nha-223',
    authDomain: 'nha-223.firebaseapp.com',
    storageBucket: 'nha-223.firebasestorage.app',
    measurementId: 'G-222E3FKEMT',
  );

}